// Generated by scripts/sync-provider-brand-paths.mjs — minimal fallback when sync has not run.
export const PROVIDER_BRAND_PATHS = {
  anthropic: 'M12 2L2 19h20L12 2z',
  openai: 'M12 2a10 10 0 100 20 10 10 0 000-20z',
  gemini: 'M12 2l8 14H4l8-14z',
  ollama: 'M4 4h16v16H4V4z',
  deepseek: 'M3 12h18',
  groq: 'M6 6h12v12H6V6z',
  openrouter: 'M4 8h16v8H4V8z',
  xai: 'M12 3l9 18H3L12 3z',
  mistral: 'M5 5h14v14H5V5z',
  arcee: 'M12 2l10 20H2L12 2z',
  cohere: 'M12 2a10 10 0 100 20 10 10 0 000-20z',
  google: 'M12 2a10 10 0 100 20 10 10 0 000-20z',
  meta: 'M12 2a10 10 0 100 20 10 10 0 000-20z',
  microsoft: 'M3 3h8v8H3V3zm10 0h8v8h-8V3zM3 13h8v8H3v-8zm10 0h8v8h-8v-8z',
  nvidia: 'M4 6h16v12H4V6z',
  perplexity: 'M12 2l8 14H4l8-14z',
  qwen: 'M12 2l10 20H2L12 2z'
} as const

export type ProviderBrandSlug = keyof typeof PROVIDER_BRAND_PATHS

export const PROVIDER_BRAND_ALIASES: Record<string, ProviderBrandSlug> = {
  'meta-llama': 'meta',
  'x-ai': 'xai'
}

export function resolveProviderBrandSlug(key: string): ProviderBrandSlug | undefined {
  const normalized = key.toLowerCase()
  if (normalized in PROVIDER_BRAND_PATHS) return normalized as ProviderBrandSlug
  return PROVIDER_BRAND_ALIASES[normalized]
}
